# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1412163124);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1412163244);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1412243325);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 1412163364);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1412163004);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1412236005);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 215040);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.migration.version", 31);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "NO");
user_pref("browser.search.region", "NO");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140830211128");
user_pref("browser.slowStartup.averageTime", 1356);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "http://www.deichman.no/");
user_pref("browser.startup.homepage_override.buildID", "20160106234645");
user_pref("browser.startup.homepage_override.mstone", "43.0.4");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1452782910484");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1452700211481");
user_pref("datareporting.policy.firstRunTime", "1452696510484");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1538);
user_pref("datareporting.sessions.current.main", 92);
user_pref("datareporting.sessions.current.sessionRestored", 1374);
user_pref("datareporting.sessions.current.startTime", "1452700200108");
user_pref("datareporting.sessions.current.totalTime", 24);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1452696509921,\"a\":2,\"t\":12,\"c\":true,\"m\":191,\"fp\":1983,\"sr\":1652}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1452699960105,\"a\":0,\"t\":0,\"c\":true,\"m\":60,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1452699966660,\"a\":0,\"t\":0,\"c\":true,\"m\":12,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1452699966833,\"a\":0,\"t\":0,\"c\":true,\"m\":32,\"fp\":-1,\"sr\":-1}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"43.0.4\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"43.0.4\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-nb-NO@firefox.mozilla.org\":{\"version\":\"43.0.4\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-nb-NO@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:43.0.4");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "43.0.4");
user_pref("extensions.lastPlatformVersion", "43.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"43.0.4\",\"st\":1452618552000,\"mt\":1452126731000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"43.0.4\",\"st\":1452127692000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"43.0.4\",\"st\":1452127692000},\"langpack-nb-NO@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-nb-NO@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"43.0.4\",\"st\":1452127755000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160106234645");
user_pref("gecko.mstone", "43.0.4");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 12984);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1452700200);
user_pref("toolkit.telemetry.cachedClientID", "279df62f-ef55-4085-bca3-5f73bb03a7a3");
user_pref("toolkit.telemetry.previousBuildID", "20160106234645");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
