#!/bin/sh
# Filename:     /etc/dhcp/dhclient-exit-hooks.d/hostname
# Purpose:      Used by dhclient-script to set the hostname of the system
#               to match the DNS information for the host as provided by
#               DHCP.
#


# Do not update hostname for virtual machine IP assignments
if [ "$interface" != "eth0" ] && [ "$interface" != "wlan0" ]
then
    return
fi


if [ "$reason" != BOUND ] && [ "$reason" != RENEW ] \
   && [ "$reason" != REBIND ] && [ "$reason" != REBOOT ]
then
        return
fi

echo "dhclient-exit-hooks.d/hostname: Dynamic IP address = $new_ip_address"
hostname=$(host $new_ip_address | cut -d ' ' -f 5 | cut -d '.' -f 1)
# NXDOMAIN means host lookup failed
if [[ $hostname != *NXDOMAIN* ]]
then
  echo $hostname > /etc/hostname
  sed -i "s/^127.0.1.1.*$/127.0.1.1    $hostname/" /etc/hosts
  hostname $hostname
  echo "dhclient-exit-hooks.d/hostname: Dynamic Hostname = $hostname"
fi
